from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

RAW_TMDB_PATH = Path("data/raw/tmdb/movies_metadata.csv")
EXCLUSIONS_PATH = Path("data/processed/television_exclusions.json")

TMDB_MOVIE_ENDPOINT = "https://api.themoviedb.org/3/movie/{tmdb_id}"
REQUEST_TIMEOUT_SECONDS = 10
MAX_WORKERS = 8
RUNTIME_PROBE_THRESHOLD_MINUTES = 180

KEEP_DESPITE_404: dict[int, str] = {
    42611: "The Sorrow and the Pity (1969) - Ophuls' theatrical documentary, "
    "Oscar-nominated for Best Documentary Feature. TMDB has no record under "
    "this id; search returns only a 2024 documentary about it.",
    55676: "A Personal Journey with Martin Scorsese Through American Movies "
    "(1995) - BFI documentary feature, catalogued as a film.",
    75964: "George Harrison: Living in the Material World (2011) - Scorsese "
    "documentary feature; TMDB serves it as a movie under id 1676821.",
    57403: "Mysteries of Lisbon (2010) - Ruiz; released theatrically as a "
    "272-min feature; TMDB serves it as a movie under id 1474601.",
    53094: "World on a Wire (1973) - Fassbinder; made for WDR but a single "
    "work restored and released theatrically in 2010, so it falls under the "
    "made-for-TV-film rule rather than the series rule.",
}


def _tmdb_request(tmdb_id: int) -> urllib.request.Request:
    """Build an authenticated request, accepting a v3 key or a v4 bearer token."""
    api_key = os.getenv("TMDB_API_KEY", "").strip()
    url = TMDB_MOVIE_ENDPOINT.format(tmdb_id=tmdb_id)
    if api_key.count(".") == 2:
        return urllib.request.Request(
            url, headers={"Authorization": f"Bearer {api_key}"}
        )
    return urllib.request.Request(f"{url}?api_key={api_key}")


def is_movie(tmdb_id: int) -> bool | None:

    try:
        with urllib.request.urlopen(
            _tmdb_request(tmdb_id), timeout=REQUEST_TIMEOUT_SECONDS
        ) as response:
            json.loads(response.read().decode("utf-8"))
        return True
    except urllib.error.HTTPError as exc:
        return False if exc.code == 404 else None
    except OSError, ValueError:
        return None


def load_probe_candidates() -> pd.DataFrame:
    """Raw TMDB records long enough to be worth checking."""
    raw = pd.read_csv(RAW_TMDB_PATH, low_memory=False)
    raw["tmdbId"] = pd.to_numeric(raw["id"], errors="coerce")
    raw["runtime"] = pd.to_numeric(raw["runtime"], errors="coerce")
    raw = raw.dropna(subset=["tmdbId"])
    raw["tmdbId"] = raw["tmdbId"].astype(int)

    candidates = raw[raw["runtime"] > RUNTIME_PROBE_THRESHOLD_MINUTES]
    return candidates.drop_duplicates(subset="tmdbId")[["tmdbId", "title", "runtime"]]


def sweep() -> dict:
    if not os.getenv("TMDB_API_KEY", "").strip():
        raise SystemExit(
            "TMDB_API_KEY is not set. The sweep needs it to classify candidates; "
            f"the committed {EXCLUSIONS_PATH} is used by the pipeline meanwhile."
        )

    candidates = load_probe_candidates()
    logger.info(
        "Probing %d TMDB records with runtime > %d min against the movie endpoint.",
        len(candidates),
        RUNTIME_PROBE_THRESHOLD_MINUTES,
    )

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:
        verdicts = list(pool.map(is_movie, candidates["tmdbId"]))

    candidates = candidates.assign(is_movie=verdicts)  # type: ignore
    unknown = candidates[candidates["is_movie"].isna()]
    if len(unknown):
        logger.warning(
            "%d records could not be classified (network errors); they are kept.",
            len(unknown),
        )

    not_movies = candidates[candidates["is_movie"] == False]  # noqa: E712
    before_overrides = len(not_movies)
    not_movies = not_movies[~not_movies["tmdbId"].isin(KEEP_DESPITE_404)]
    logger.info(
        "Classified %d of %d probed records as television (%d reinstated by the "
        "reviewed keep-list).",
        len(not_movies),
        len(candidates),
        before_overrides - len(not_movies),
    )

    return {
        "_comment": (
            "TMDB ids that the raw movies_metadata.csv labels as movies but that "
            "TMDB's own /3/movie/{id} endpoint does not serve -- television "
            "records. Generated by src/television_filter.py; committed so the "
            "pipeline reproduces offline."
        ),
        "probe_runtime_threshold_minutes": RUNTIME_PROBE_THRESHOLD_MINUTES,
        "probed": int(len(candidates)),
        "reinstated_by_review": {str(k): v for k, v in KEEP_DESPITE_404.items()},
        "excluded_tmdb_ids": sorted(int(t) for t in not_movies["tmdbId"]),
        "excluded_titles": {
            str(int(row.tmdbId)): f"{row.title} ({int(row.runtime)} min)"  # type: ignore
            for row in not_movies.itertuples()
        },
    }


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    payload = sweep()
    EXCLUSIONS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(EXCLUSIONS_PATH, "w") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
    logger.info(
        "Wrote %d television exclusions to %s.",
        len(payload["excluded_tmdb_ids"]),
        EXCLUSIONS_PATH,
    )


if __name__ == "__main__":
    main()
